CREATE TABLE KHACHHANG
(
	Userr CHAR(20) NOT NULL ,
	Password CHAR(50) NOT NULL ,
	EMAIL NCHAR(50)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (Userr,Password) 
)

insert into KHACHHANG
VALUES ('ADMIN','123','ADMIN123@GMAIL.COM')